## DB CONNECTION ##
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:agridb}?serverTimezone=UTC
spring.datasource.username=${MYSQL_USER:agriuser}
spring.datasource.password=${MYSQL_PASSWORD:12345}

## Το Hibernate δημιουργεί και ενημερώνει το σχήμα από τα entities.
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.show_sql=true

## SEED DATA ##
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:sql/roles_capabilities.sql,classpath:sql/crop_types.sql,classpath:sql/products.sql,classpath:sql/pests.sql
#spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8
spring.sql.init.platform=mysql

## Σιωπά ψευδές warning για AuthenticationManager / UserDetailsService
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
